M48
; DRILL file {KiCad 9.0.9-9.0.9~ubuntu24.04.1} date 2026-10-04T10:42:00+0000
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-10-04T10:42:00+00:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.9-9.0.9~ubuntu24.04.1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.200
%
G90
G05
T1
X87.356Y-107.3
X100.0Y-85.4
X112.644Y-107.3
M30
